# Site settings
title: Daniel Anggrianto
description: Portfolio For Daniel Anggrianto
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Anggrianto
user_description: Expert in Automation and Continuous Testing
user_title: Automation QA Engineer
email: daniel@anggrianto.com
twitter_username: danggrianto
github_username:  danggrianto

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman
